In [9]:
import numpy as np

np_array = np.array([
        [7, 4, 8],
       [3, 6, 1],
       [2, 8, 4]]
)

print(np_array.mean(axis=1))
print(np_array.std(axis=0))
print(np_array.sum())

[6.33333333 3.33333333 4.66666667]
[2.1602469  1.63299316 2.86744176]
43


In [15]:
a = np.array([
       [7, 7, 1, 4],
       [4, 2, 6, 9],
       [6, 3, 7, 5]])

b = np.array([
       [9, 5, 5, 8],
       [8, 3, 6, 2],
       [1, 7, 9, 9]])

conc = np.concatenate([a,b])
print(conc)

[[7 7 1 4]
 [4 2 6 9]
 [6 3 7 5]
 [9 5 5 8]
 [8 3 6 2]
 [1 7 9 9]]


In [17]:
a = np.array([
       [27,  2,  7],
       [ 1, 27, 11],
       [26, 22, 27],
       [22, 24, 22],
       [19, 27, 20]])

print(a.max())
print(a.min())

27
1


In [31]:
a = np.array([
       [12, 4],
       [15, 18],
       [4, 23],
       [17, 22],
       [22, 22],
       [21, 17],
       [28, 23],
       [27, 18]])


print(a.transpose().flatten())

[12 15  4 17 22 21 28 27  4 18 23 22 22 17 23 18]
